# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "25c0b9f75b1285453fbdc65d995f07c7"
name = "memofox"
handle = "memofox-2"
application_url = "https://tunisia-poem-metallic-amanda.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "memofox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://tunisia-poem-metallic-amanda.trycloudflare.com/auth/callback",
  "https://tunisia-poem-metallic-amanda.trycloudflare.com/auth/shopify/callback",
  "https://tunisia-poem-metallic-amanda.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
