# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9342b92fd72339c05a9b8b640b41ce2f"
name = "Memofox"
handle = "memofox-1"
application_url = "https://fo-scheduling-pavilion-curriculum.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "memofox.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://fo-scheduling-pavilion-curriculum.trycloudflare.com/auth/callback",
  "https://fo-scheduling-pavilion-curriculum.trycloudflare.com/auth/shopify/callback",
  "https://fo-scheduling-pavilion-curriculum.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
